# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lookup.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='lookup.proto',
  package='lookup',
  syntax='proto3',
  serialized_pb=_b('\n\x0clookup.proto\x12\x06lookup\"\x1d\n\x0eRequestMessage\x12\x0b\n\x03key\x18\x01 \x01(\t\"\x17\n\x06ValAck\x12\r\n\x05value\x18\x01 \x01(\t\" \n\x06Params\x12\n\n\x02id\x18\x01 \x01(\t\x12\n\n\x02ip\x18\x02 \x01(\t\"\x1e\n\x0fResponseMessage\x12\x0b\n\x03msg\x18\x01 \x01(\t2z\n\x0bMainService\x12\x34\n\x08Retrieve\x12\x16.lookup.RequestMessage\x1a\x0e.lookup.ValAck\"\x00\x12\x35\n\x08Register\x12\x0e.lookup.Params\x1a\x17.lookup.ResponseMessage\"\x00\x62\x06proto3')
)




_REQUESTMESSAGE = _descriptor.Descriptor(
  name='RequestMessage',
  full_name='lookup.RequestMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='lookup.RequestMessage.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=53,
)


_VALACK = _descriptor.Descriptor(
  name='ValAck',
  full_name='lookup.ValAck',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='lookup.ValAck.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=78,
)


_PARAMS = _descriptor.Descriptor(
  name='Params',
  full_name='lookup.Params',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='lookup.Params.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ip', full_name='lookup.Params.ip', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=112,
)


_RESPONSEMESSAGE = _descriptor.Descriptor(
  name='ResponseMessage',
  full_name='lookup.ResponseMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='lookup.ResponseMessage.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=144,
)

DESCRIPTOR.message_types_by_name['RequestMessage'] = _REQUESTMESSAGE
DESCRIPTOR.message_types_by_name['ValAck'] = _VALACK
DESCRIPTOR.message_types_by_name['Params'] = _PARAMS
DESCRIPTOR.message_types_by_name['ResponseMessage'] = _RESPONSEMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RequestMessage = _reflection.GeneratedProtocolMessageType('RequestMessage', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTMESSAGE,
  __module__ = 'lookup_pb2'
  # @@protoc_insertion_point(class_scope:lookup.RequestMessage)
  ))
_sym_db.RegisterMessage(RequestMessage)

ValAck = _reflection.GeneratedProtocolMessageType('ValAck', (_message.Message,), dict(
  DESCRIPTOR = _VALACK,
  __module__ = 'lookup_pb2'
  # @@protoc_insertion_point(class_scope:lookup.ValAck)
  ))
_sym_db.RegisterMessage(ValAck)

Params = _reflection.GeneratedProtocolMessageType('Params', (_message.Message,), dict(
  DESCRIPTOR = _PARAMS,
  __module__ = 'lookup_pb2'
  # @@protoc_insertion_point(class_scope:lookup.Params)
  ))
_sym_db.RegisterMessage(Params)

ResponseMessage = _reflection.GeneratedProtocolMessageType('ResponseMessage', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSEMESSAGE,
  __module__ = 'lookup_pb2'
  # @@protoc_insertion_point(class_scope:lookup.ResponseMessage)
  ))
_sym_db.RegisterMessage(ResponseMessage)



_MAINSERVICE = _descriptor.ServiceDescriptor(
  name='MainService',
  full_name='lookup.MainService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=146,
  serialized_end=268,
  methods=[
  _descriptor.MethodDescriptor(
    name='Retrieve',
    full_name='lookup.MainService.Retrieve',
    index=0,
    containing_service=None,
    input_type=_REQUESTMESSAGE,
    output_type=_VALACK,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Register',
    full_name='lookup.MainService.Register',
    index=1,
    containing_service=None,
    input_type=_PARAMS,
    output_type=_RESPONSEMESSAGE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MAINSERVICE)

DESCRIPTOR.services_by_name['MainService'] = _MAINSERVICE

# @@protoc_insertion_point(module_scope)
