# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: phase1.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='phase1.proto',
  package='phase1',
  syntax='proto3',
  serialized_pb=_b('\n\x0cphase1.proto\x12\x06phase1\"\x1c\n\nJamRequest\x12\x0e\n\x06nodeId\x18\x01 \x01(\x05\"\"\n\x0bJamResponse\x12\x13\n\x0bjamResponse\x18\x01 \x01(\t\"/\n\x0b\x43lusterName\x12\x13\n\x0b\x63lusterName\x18\x01 \x01(\t\x12\x0b\n\x03hop\x18\x02 \x01(\x05\" \n\nClusterAck\x12\x12\n\nclusterAck\x18\x01 \x01(\t\"\x16\n\x06MySize\x12\x0c\n\x04size\x18\x01 \x01(\x05\"\"\n\x0f\x41\x63\x63omodateChild\x12\x0f\n\x07message\x18\x01 \x01(\t\"H\n\x0eRequestMessage\x12\x0e\n\x06nodeId\x18\x01 \x01(\t\x12\x15\n\rdestinationId\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"L\n\x0fResponseMessage\x12\x0e\n\x06nodeId\x18\x01 \x01(\t\x12\x15\n\rdestinationId\x18\x02 \x01(\t\x12\x12\n\nackMessage\x18\x03 \x01(\t\"J\n\x0cShiftRequest\x12\x0e\n\x06nodeId\x18\x01 \x01(\t\x12\x13\n\x0bsumOfweight\x18\x02 \x01(\x05\x12\x15\n\rclusterHeadId\x18\x03 \x01(\t\" \n\rShiftResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xec\x02\n\x0bMainService\x12>\n\tHandshake\x12\x16.phase1.RequestMessage\x1a\x17.phase1.ResponseMessage\"\x00\x12?\n\nSendPacket\x12\x16.phase1.RequestMessage\x1a\x17.phase1.ResponseMessage\"\x00\x12\x31\n\x04Size\x12\x0e.phase1.MySize\x1a\x17.phase1.AccomodateChild\"\x00\x12\x34\n\x07\x43luster\x12\x13.phase1.ClusterName\x1a\x12.phase1.ClusterAck\"\x00\x12\x41\n\x10ShiftNodeRequest\x12\x14.phase1.ShiftRequest\x1a\x15.phase1.ShiftResponse\"\x00\x12\x30\n\x03Jam\x12\x12.phase1.JamRequest\x1a\x13.phase1.JamResponse\"\x00\x62\x06proto3')
)




_JAMREQUEST = _descriptor.Descriptor(
  name='JamRequest',
  full_name='phase1.JamRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nodeId', full_name='phase1.JamRequest.nodeId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=52,
)


_JAMRESPONSE = _descriptor.Descriptor(
  name='JamResponse',
  full_name='phase1.JamResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='jamResponse', full_name='phase1.JamResponse.jamResponse', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=88,
)


_CLUSTERNAME = _descriptor.Descriptor(
  name='ClusterName',
  full_name='phase1.ClusterName',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='clusterName', full_name='phase1.ClusterName.clusterName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hop', full_name='phase1.ClusterName.hop', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=137,
)


_CLUSTERACK = _descriptor.Descriptor(
  name='ClusterAck',
  full_name='phase1.ClusterAck',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='clusterAck', full_name='phase1.ClusterAck.clusterAck', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=139,
  serialized_end=171,
)


_MYSIZE = _descriptor.Descriptor(
  name='MySize',
  full_name='phase1.MySize',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='size', full_name='phase1.MySize.size', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=195,
)


_ACCOMODATECHILD = _descriptor.Descriptor(
  name='AccomodateChild',
  full_name='phase1.AccomodateChild',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='phase1.AccomodateChild.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=197,
  serialized_end=231,
)


_REQUESTMESSAGE = _descriptor.Descriptor(
  name='RequestMessage',
  full_name='phase1.RequestMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nodeId', full_name='phase1.RequestMessage.nodeId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='destinationId', full_name='phase1.RequestMessage.destinationId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='phase1.RequestMessage.message', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=233,
  serialized_end=305,
)


_RESPONSEMESSAGE = _descriptor.Descriptor(
  name='ResponseMessage',
  full_name='phase1.ResponseMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nodeId', full_name='phase1.ResponseMessage.nodeId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='destinationId', full_name='phase1.ResponseMessage.destinationId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ackMessage', full_name='phase1.ResponseMessage.ackMessage', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=307,
  serialized_end=383,
)


_SHIFTREQUEST = _descriptor.Descriptor(
  name='ShiftRequest',
  full_name='phase1.ShiftRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nodeId', full_name='phase1.ShiftRequest.nodeId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sumOfweight', full_name='phase1.ShiftRequest.sumOfweight', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='clusterHeadId', full_name='phase1.ShiftRequest.clusterHeadId', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=385,
  serialized_end=459,
)


_SHIFTRESPONSE = _descriptor.Descriptor(
  name='ShiftResponse',
  full_name='phase1.ShiftResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='phase1.ShiftResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=461,
  serialized_end=493,
)

DESCRIPTOR.message_types_by_name['JamRequest'] = _JAMREQUEST
DESCRIPTOR.message_types_by_name['JamResponse'] = _JAMRESPONSE
DESCRIPTOR.message_types_by_name['ClusterName'] = _CLUSTERNAME
DESCRIPTOR.message_types_by_name['ClusterAck'] = _CLUSTERACK
DESCRIPTOR.message_types_by_name['MySize'] = _MYSIZE
DESCRIPTOR.message_types_by_name['AccomodateChild'] = _ACCOMODATECHILD
DESCRIPTOR.message_types_by_name['RequestMessage'] = _REQUESTMESSAGE
DESCRIPTOR.message_types_by_name['ResponseMessage'] = _RESPONSEMESSAGE
DESCRIPTOR.message_types_by_name['ShiftRequest'] = _SHIFTREQUEST
DESCRIPTOR.message_types_by_name['ShiftResponse'] = _SHIFTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

JamRequest = _reflection.GeneratedProtocolMessageType('JamRequest', (_message.Message,), dict(
  DESCRIPTOR = _JAMREQUEST,
  __module__ = 'phase1_pb2'
  # @@protoc_insertion_point(class_scope:phase1.JamRequest)
  ))
_sym_db.RegisterMessage(JamRequest)

JamResponse = _reflection.GeneratedProtocolMessageType('JamResponse', (_message.Message,), dict(
  DESCRIPTOR = _JAMRESPONSE,
  __module__ = 'phase1_pb2'
  # @@protoc_insertion_point(class_scope:phase1.JamResponse)
  ))
_sym_db.RegisterMessage(JamResponse)

ClusterName = _reflection.GeneratedProtocolMessageType('ClusterName', (_message.Message,), dict(
  DESCRIPTOR = _CLUSTERNAME,
  __module__ = 'phase1_pb2'
  # @@protoc_insertion_point(class_scope:phase1.ClusterName)
  ))
_sym_db.RegisterMessage(ClusterName)

ClusterAck = _reflection.GeneratedProtocolMessageType('ClusterAck', (_message.Message,), dict(
  DESCRIPTOR = _CLUSTERACK,
  __module__ = 'phase1_pb2'
  # @@protoc_insertion_point(class_scope:phase1.ClusterAck)
  ))
_sym_db.RegisterMessage(ClusterAck)

MySize = _reflection.GeneratedProtocolMessageType('MySize', (_message.Message,), dict(
  DESCRIPTOR = _MYSIZE,
  __module__ = 'phase1_pb2'
  # @@protoc_insertion_point(class_scope:phase1.MySize)
  ))
_sym_db.RegisterMessage(MySize)

AccomodateChild = _reflection.GeneratedProtocolMessageType('AccomodateChild', (_message.Message,), dict(
  DESCRIPTOR = _ACCOMODATECHILD,
  __module__ = 'phase1_pb2'
  # @@protoc_insertion_point(class_scope:phase1.AccomodateChild)
  ))
_sym_db.RegisterMessage(AccomodateChild)

RequestMessage = _reflection.GeneratedProtocolMessageType('RequestMessage', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTMESSAGE,
  __module__ = 'phase1_pb2'
  # @@protoc_insertion_point(class_scope:phase1.RequestMessage)
  ))
_sym_db.RegisterMessage(RequestMessage)

ResponseMessage = _reflection.GeneratedProtocolMessageType('ResponseMessage', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSEMESSAGE,
  __module__ = 'phase1_pb2'
  # @@protoc_insertion_point(class_scope:phase1.ResponseMessage)
  ))
_sym_db.RegisterMessage(ResponseMessage)

ShiftRequest = _reflection.GeneratedProtocolMessageType('ShiftRequest', (_message.Message,), dict(
  DESCRIPTOR = _SHIFTREQUEST,
  __module__ = 'phase1_pb2'
  # @@protoc_insertion_point(class_scope:phase1.ShiftRequest)
  ))
_sym_db.RegisterMessage(ShiftRequest)

ShiftResponse = _reflection.GeneratedProtocolMessageType('ShiftResponse', (_message.Message,), dict(
  DESCRIPTOR = _SHIFTRESPONSE,
  __module__ = 'phase1_pb2'
  # @@protoc_insertion_point(class_scope:phase1.ShiftResponse)
  ))
_sym_db.RegisterMessage(ShiftResponse)



_MAINSERVICE = _descriptor.ServiceDescriptor(
  name='MainService',
  full_name='phase1.MainService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=496,
  serialized_end=860,
  methods=[
  _descriptor.MethodDescriptor(
    name='Handshake',
    full_name='phase1.MainService.Handshake',
    index=0,
    containing_service=None,
    input_type=_REQUESTMESSAGE,
    output_type=_RESPONSEMESSAGE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendPacket',
    full_name='phase1.MainService.SendPacket',
    index=1,
    containing_service=None,
    input_type=_REQUESTMESSAGE,
    output_type=_RESPONSEMESSAGE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Size',
    full_name='phase1.MainService.Size',
    index=2,
    containing_service=None,
    input_type=_MYSIZE,
    output_type=_ACCOMODATECHILD,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Cluster',
    full_name='phase1.MainService.Cluster',
    index=3,
    containing_service=None,
    input_type=_CLUSTERNAME,
    output_type=_CLUSTERACK,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ShiftNodeRequest',
    full_name='phase1.MainService.ShiftNodeRequest',
    index=4,
    containing_service=None,
    input_type=_SHIFTREQUEST,
    output_type=_SHIFTRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Jam',
    full_name='phase1.MainService.Jam',
    index=5,
    containing_service=None,
    input_type=_JAMREQUEST,
    output_type=_JAMRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MAINSERVICE)

DESCRIPTOR.services_by_name['MainService'] = _MAINSERVICE

# @@protoc_insertion_point(module_scope)
