SPANNING_INFO = {'0':{'parentId':None,
					'childListId':['1','2'],
					'dist':None,
					'clusterheadId':None,
					'subtreeList':[1,2,3,4,5,6],
					'neighbourList':None,
					'weight':None,
					'childWeightList':None,
					'isClusterhead':None,
					'state':"active",
					'rackLocation':'0,0'
				},
				 '1':{'parentId':'0',
					'childListId':['3','5'],
					'dist':None,
					'clusterheadId':None,
					'subtreeList':[3,5],
					'neighbourList':None,
					'weight':None,
					'childWeightList':None,
					'isClusterhead':None,
					'state':"active",
					'rackLocation':'0,1'
				},
				 '2':{'parentId':'0',
					'childListId':['4','7'],
					'dist':None,
					'clusterheadId':None,
					'subtreeList':[1,2,3,4,5,6],
					'neighbourList':None,
					'weight':None,
					'childWeightList':None,
					'isClusterhead':None,
					'state':"active",
					'rackLocation':'0,2'
				},
				 '3':{'parentId':'1',
					'childListId':None,
					'dist':None,
					'clusterheadId':None,
					'subtreeList':None,
					'neighbourList':None,
					'weight':None,
					'childWeightList':None,
					'isClusterhead':None,
					'state':"active",
					'rackLocation':'1,0'
				},
				 '4':{'parentId':'2',
					'childListId':['9'],
					'dist':None,
					'clusterheadId':None,
					'subtreeList':None,
					'neighbourList':None,
					'weight':None,
					'childWeightList':None,
					'isClusterhead':None,
					'state':"active",
					'rackLocation':'1,1'
				},
				 '5':{'parentId':'1',
					'childListId':['11'],
					'dist':None,
					'clusterheadId':None,
					'subtreeList':None,
					'neighbourList':None,
					'weight':None,
					'childWeightList':None,
					'isClusterhead':None,
					'state':"active",
					'rackLocation':'1,2'
				},
				'6':{'parentId':'7',
					'childListId':None,
					'dist':None,
					'clusterheadId':None,
					'subtreeList':None,
					'neighbourList':None,
					'weight':None,
					'childWeightList':None,
					'isClusterhead':None,
					'state':"active",
					'rackLocation':'2,0'
				},
				'7':{'parentId':'2',
					'childListId':['6','8'],
					'dist':None,
					'clusterheadId':None,
					'subtreeList':None,
					'neighbourList':None,
					'weight':None,
					'childWeightList':None,
					'isClusterhead':None,
					'state':"active",
					'rackLocation':'2,1'
				},
				 '8': {'parentId': '7',
					 'childListId': [10],
					 'dist': None,
					 'clusterheadId': None,
					 'subtreeList': None,
					 'neighbourList': None,
					 'weight': None,
					 'childWeightList': None,
					 'isClusterhead': None,
					 'state': "active",
					 'rackLocation': '2,2'
					 },
				 '9': {'parentId': '4',
					 'childListId': None,
					 'dist': None,
					 'clusterheadId': None,
					 'subtreeList': None,
					 'neighbourList': None,
					 'weight': None,
					 'childWeightList': None,
					 'isClusterhead': None,
					 'state': "active",
					 'rackLocation': '0,3'
					 },
				 '10': {'parentId': '8',
					 'childListId': None,
					 'dist': None,
					 'clusterheadId': None,
					 'subtreeList': None,
					 'neighbourList': None,
					 'weight': None,
					 'childWeightList': None,
					 'isClusterhead': None,
					 'state': "active",
					 'rackLocation': '1,3'
					 },
				 '11': {'parentId': '5',
					 'childListId': None,
					 'dist': None,
					 'clusterheadId': None,
					 'subtreeList': None,
					 'neighbourList': None,
					 'weight': None,
					 'childWeightList': None,
					 'isClusterhead': None,
					 'state': "active",
					 'rackLocation': '2,4'
					 }
				 }