from pymongo import MongoClient

from time import sleep

con = MongoClient('mongodb://localhost:27017/')
db = con.spanningtreemap

def populateTree():
	print("Inserting spanning tree into mongoDB....")
	db.spanningtree.insert([{
						'nodeId':'0',
						'parentId':None,
						'childListId':['1','2'],
						'dist':None,
						'clusterheadId':None,
						'subtreeList':[1,2,3,4,5,6],
						'neighbourList':None,
						'weight':None,
						'childWeightList':None,
						'isClusterhead':None,
						'state':"active",
						'rackLocation':'0,0'
					},
					 {	'nodeId':'1',
						'parentId':'0',
						'childListId':['3','5'],
						'dist':None,
						'clusterheadId':None,
						'subtreeList':['3','5'],
						'neighbourList':None,
						'weight':None,
						'childWeightList':None,
						'isClusterhead':None,
						'state':"active",
						'rackLocation':'0,1'
					},
					 {	'nodeId':'2',
						'parentId':'0',
						'childListId':['4','6'],
						'dist':None,
						'clusterheadId':None,
						'subtreeList':[1,2,3,4,5,6],
						'neighbourList':None,
						'weight':None,
						'childWeightList':None,
						'isClusterhead':None,
						'state':"active",
						'rackLocation':'0,2'
					},
						{'nodeId':'3',
						'parentId':'1',
						'childListId':None,
						'dist':None,
						'clusterheadId':None,
						'subtreeList':None,
						'neighbourList':None,
						'weight':None,
						'childWeightList':None,
						'isClusterhead':None,
						'state':"active",
						'rackLocation':'1,0'
					},
						{'nodeId':'4',
						'parentId':'2',
						'childListId':['9'],
						'dist':None,
						'clusterheadId':None,
						'subtreeList':None,
						'neighbourList':None,
						'weight':None,
						'childWeightList':None,
						'isClusterhead':None,
						'state':"active",
						'rackLocation':'1,1'
					},
					 {'nodeId':'5',
						 'parentId':'1',
						'childListId':['11'],
						'dist':None,
						'clusterheadId':None,
						'subtreeList':None,
						'neighbourList':None,
						'weight':None,
						'childWeightList':None,
						'isClusterhead':None,
						'state':"active",
						'rackLocation':'1,2'
					},
					{	'nodeId':'6',
						 'parentId': '2',
						 'childListId': ['7', '8'],
						 'dist': None,
						 'clusterheadId': None,
						 'subtreeList': None,
						 'neighbourList': None,
						 'weight': None,
						 'childWeightList': None,
						 'isClusterhead': None,
						 'state': "active",
						 'rackLocation': '2,1'
					},
					{	'nodeId':'7',
						'parentId':'6',
						'childListId':None,
						'dist':None,
						'clusterheadId':None,
						'subtreeList':None,
						'neighbourList':None,
					 	'weight':None,
					   	'childWeightList':None,
					    'isClusterhead':None,
					    'state':"active",
					    'rackLocation':'2,0'
					},
					{	'nodeId':'8',
						'parentId': '6',
						 'childListId': ['10'],
						 'dist': None,
						 'clusterheadId': None,
						 'subtreeList': None,
						 'neighbourList': None,
						 'weight': None,
						 'childWeightList': None,
						 'isClusterhead': None,
						 'state': "active",
						 'rackLocation': '2,2'
						 },
						{'nodeId':'9',
						'parentId': '4',
						 'childListId':None,
						 'dist': None,
						 'clusterheadId': None,
						 'subtreeList': None,
						 'neighbourList': None,
						 'weight': None,
						 'childWeightList': None,
						 'isClusterhead': None,
						 'state': "active",
						 'rackLocation': '0,3'
						 },
						{'nodeId':'10',
						'parentId': '8',
						 'childListId':None,
						 'dist': None,
						 'clusterheadId': None,
						 'subtreeList': None,
						 'neighbourList': None,
						 'weight': None,
						 'childWeightList': None,
						 'isClusterhead': None,
						 'state': "active",
						 'rackLocation': '1,3'
						 },
						{'nodeId':'11',
						'parentId': '5',
						 'childListId': None,
						 'dist': None,
						 'clusterheadId': None,
						 'subtreeList': None,
						 'neighbourList': None,
						 'weight': None,
						 'childWeightList': None,
						 'isClusterhead': None,
						 'state': "active",
						 'rackLocation': '2,3'
						 },
						# {'nodeId':'12',
						#  'parentId': '11',
						#  'childListId': ['13'],
						#  'dist': None,
						#  'clusterheadId': None,
						#  'subtreeList': None,
						#  'neighbourList': None,
						#  'weight': None,
						#  'childWeightList': None,
						#  'isClusterhead': None,
						#  'state': "active",
						#  'rackLocation': '3,0'
						#  },
						# {'nodeId':'13',
						#  'parentId': '12',
						#  'childListId': ['21'],
						#  'dist': None,
						#  'clusterheadId': None,
						#  'subtreeList': None,
						#  'neighbourList': None,
						#  'weight': None,
						#  'childWeightList': None,
						#  'isClusterhead': None,
						#  'state': "active",
						#  'rackLocation': '3,1'
						#  },
						# {'nodeId':'14',
						#  'parentId': '6',
						#  'childListId': ['15'],
						#  'dist': None,
						#  'clusterheadId': None,
						#  'subtreeList': None,
						#  'neighbourList': None,
						#  'weight': None,
						#  'childWeightList': None,
						#  'isClusterhead': None,
						#  'state': "active",
						#  'rackLocation': '3,2'
						#  },
						# {'nodeId':'15',
						#  'parentId': '14',
						#  'childListId': ['16'],
						#  'dist': None,
						#  'clusterheadId': None,
						#  'subtreeList': None,
						#  'neighbourList': None,
						#  'weight': None,
						#  'childWeightList': None,
						#  'isClusterhead': None,
						#  'state': "active",
						#  'rackLocation': '3,3'
						#  },
						# {'nodeId':'16',
						#  'parentId': '15',
						#  'childListId': ['17'],
						#  'dist': None,
						#  'clusterheadId': None,
						#  'subtreeList': None,
						#  'neighbourList': None,
						#  'weight': None,
						#  'childWeightList': None,
						#  'isClusterhead': None,
						#  'state': "active",
						#  'rackLocation': '0,4'
						#  },
						# {'nodeId':'17',
						#  'parentId': '16',
						#  'childListId': [],
						#  'dist': None,
						#  'clusterheadId': None,
						#  'subtreeList': None,
						#  'neighbourList': None,
						#  'weight': None,
						#  'childWeightList': None,
						#  'isClusterhead': None,
						#  'state': "active",
						#  'rackLocation': '1,4'
						#  },
						# {'nodeId':'18',
						#  'parentId': '10',
						#  'childListId': ['19'],
						#  'dist': None,
						#  'clusterheadId': None,
						#  'subtreeList': None,
						#  'neighbourList': None,
						#  'weight': None,
						#  'childWeightList': None,
						#  'isClusterhead': None,
						#  'state': "active",
						#  'rackLocation': '2,4'
						#  },
						# {'nodeId':'19',
						#  'parentId': '18',
						#  'childListId': [],
						#  'dist': None,
						#  'clusterheadId': None,
						#  'subtreeList': None,
						#  'neighbourList': None,
						#  'weight': None,
						#  'childWeightList': None,
						#  'isClusterhead': None,
						#  'state': "active",
						#  'rackLocation': '3,4'
						#  },
						# {'nodeId':'20',
						#  'parentId': '10',
						#  'childListId': [],
						#  'dist': None,
						#  'clusterheadId': None,
						#  'subtreeList': None,
						#  'neighbourList': None,
						#  'weight': None,
						#  'childWeightList': None,
						#  'isClusterhead': None,
						#  'state': "active",
						#  'rackLocation': '0,5'},
						# {'nodeId':'21',
						#  'parentId': '13',
						#  'childListId': [],
						#  'dist': None,
						#  'clusterheadId': None,
						#  'subtreeList': None,
						#  'neighbourList': None,
						#  'weight': None,
						#  'childWeightList': None,
						#  'isClusterhead': None,
						#  'state': "active",
						#  'rackLocation': '1,5'}

					 ])
	print("Done")