SPANNING_INFO = {'0':{'parentId':None,
					'childListId':['1','2'],
					'dist':None,
					'clusterheadId':None,
					'subtreeList':[1,2,3,4,5,6],
					'neighbourList':None,
					'weight':None,
					'childWeightList':None,
					'isClusterhead':None,
					'state':"active",
					'rackLocation':'0,0'
				},
				 '1':{'parentId':'0',
					'childListId':['3','5'],
					'dist':None,
					'clusterheadId':None,
					'subtreeList':[3,5],
					'neighbourList':None,
					'weight':None,
					'childWeightList':None,
					'isClusterhead':None,
					'state':"active",
					'rackLocation':'0,1'
				},
				 '2':{'parentId':'0',
					'childListId':['4','7'],
					'dist':None,
					'clusterheadId':None,
					'subtreeList':[1,2,3,4,5,6],
					'neighbourList':None,
					'weight':None,
					'childWeightList':None,
					'isClusterhead':None,
					'state':"active",
					'rackLocation':'0,2'
				},
				 '3':{'parentId':'1',
					'childListId':None,
					'dist':None,
					'clusterheadId':None,
					'subtreeList':None,
					'neighbourList':None,
					'weight':None,
					'childWeightList':None,
					'isClusterhead':None,
					'state':"active",
					'rackLocation':'1,0'
				},
				 '4':{'parentId':'2',
					'childListId':['9'],
					'dist':None,
					'clusterheadId':None,
					'subtreeList':None,
					'neighbourList':None,
					'weight':None,
					'childWeightList':None,
					'isClusterhead':None,
					'state':"active",
					'rackLocation':'1,1'
				},
				 '5':{'parentId':'1',
					'childListId':['11'],
					'dist':None,
					'clusterheadId':None,
					'subtreeList':None,
					'neighbourList':None,
					'weight':None,
					'childWeightList':None,
					'isClusterhead':None,
					'state':"active",
					'rackLocation':'1,2'
				},
				'6':{'parentId':'7',
					'childListId':['14'],
					'dist':None,
					'clusterheadId':None,
					'subtreeList':None,
					'neighbourList':None,
					'weight':None,
					'childWeightList':None,
					'isClusterhead':None,
					'state':"active",
					'rackLocation':'2,0'
				},
				'7':{'parentId':'2',
					'childListId':['6','8','31'],
					'dist':None,
					'clusterheadId':None,
					'subtreeList':None,
					'neighbourList':None,
					'weight':None,
					'childWeightList':None,
					'isClusterhead':None,
					'state':"active",
					'rackLocation':'2,1'
				},
				 '8': {'parentId': '7',
					 'childListId': ['10'],
					 'dist': None,
					 'clusterheadId': None,
					 'subtreeList': None,
					 'neighbourList': None,
					 'weight': None,
					 'childWeightList': None,
					 'isClusterhead': None,
					 'state': "active",
					 'rackLocation': '2,2'
					 },
				 '9': {'parentId': '4',
					 'childListId': ['24'],
					 'dist': None,
					 'clusterheadId': None,
					 'subtreeList': None,
					 'neighbourList': None,
					 'weight': None,
					 'childWeightList': None,
					 'isClusterhead': None,
					 'state': "active",
					 'rackLocation': '0,3'
					 },
				 '10': {'parentId': '8',
					 'childListId': ['18','20'],
					 'dist': None,
					 'clusterheadId': None,
					 'subtreeList': None,
					 'neighbourList': None,
					 'weight': None,
					 'childWeightList': None,
					 'isClusterhead': None,
					 'state': "active",
					 'rackLocation': '1,3'
					 },
				 '11': {'parentId': '5',
					 'childListId': ['12'],
					 'dist': None,
					 'clusterheadId': None,
					 'subtreeList': None,
					 'neighbourList': None,
					 'weight': None,
					 'childWeightList': None,
					 'isClusterhead': None,
					 'state': "active",
					 'rackLocation': '2,4'
					 },
				 '12': {'parentId': '11',
					 'childListId': ['13'],
					 'dist': None,
					 'clusterheadId': None,
					 'subtreeList': None,
					 'neighbourList': None,
					 'weight': None,
					 'childWeightList': None,
					 'isClusterhead': None,
					 'state': "active",
					 'rackLocation': '2,4'
					 },
				 '13': {'parentId': '12',
					 'childListId': ['40','21','39'],
					 'dist': None,
					 'clusterheadId': None,
					 'subtreeList': None,
					 'neighbourList': None,
					 'weight': None,
					 'childWeightList': None,
					 'isClusterhead': None,
					 'state': "active",
					 'rackLocation': '2,4'
					 },
				 '14': {'parentId': '6',
					 'childListId': ['15'],
					 'dist': None,
					 'clusterheadId': None,
					 'subtreeList': None,
					 'neighbourList': None,
					 'weight': None,
					 'childWeightList': None,
					 'isClusterhead': None,
					 'state': "active",
					 'rackLocation': '2,4'
					 },
				 '15': {'parentId': '14',
					 'childListId': ['16'],
					 'dist': None,
					 'clusterheadId': None,
					 'subtreeList': None,
					 'neighbourList': None,
					 'weight': None,
					 'childWeightList': None,
					 'isClusterhead': None,
					 'state': "active",
					 'rackLocation': '2,4'
					 },
				 '16': {'parentId': '15',
					 'childListId': ['17'],
					 'dist': None,
					 'clusterheadId': None,
					 'subtreeList': None,
					 'neighbourList': None,
					 'weight': None,
					 'childWeightList': None,
					 'isClusterhead': None,
					 'state': "active",
					 'rackLocation': '2,4'
					 },
                 '17': {'parentId': '16',
					 'childListId': ['25','26'],
					 'dist': None,
					 'clusterheadId': None,
					 'subtreeList': None,
					 'neighbourList': None,
					 'weight': None,
					 'childWeightList': None,
					 'isClusterhead': None,
					 'state': "active",
					 'rackLocation': '2,4'
					 },
			     '18': {'parentId': '10',
					 'childListId': ['19'],
					 'dist': None,
					 'clusterheadId': None,
					 'subtreeList': None,
					 'neighbourList': None,
					 'weight': None,
					 'childWeightList': None,
					 'isClusterhead': None,
					 'state': "active",
					 'rackLocation': '2,4'
					 },
			     '19': {'parentId': '18',
					 'childListId': ['27','28'],
					 'dist': None,
					 'clusterheadId': None,
					 'subtreeList': None,
					 'neighbourList': None,
					 'weight': None,
					 'childWeightList': None,
					 'isClusterhead': None,
					 'state': "active",
					 'rackLocation': '2,4'
					 },
				 '20': {'parentId': '10',
					 'childListId': ['30'],
					 'dist': None,
					 'clusterheadId': None,
					 'subtreeList': None,
					 'neighbourList': None,
					 'weight': None,
					 'childWeightList': None,
					 'isClusterhead': None,
					 'state': "active",
					 'rackLocation': '2,4'},
				 '21': {'parentId': '13',
					 'childListId': ['22','34'],
					 'dist': None,
					 'clusterheadId': None,
					 'subtreeList': None,
					 'neighbourList': None,
					 'weight': None,
					 'childWeightList': None,
					 'isClusterhead': None,
					 'state': "active",
					 'rackLocation': '2,4'},
				 '22': {'parentId': '21',
					 'childListId': ['23'],
					 'dist': None,
					 'clusterheadId': None,
					 'subtreeList': None,
					 'neighbourList': None,
					 'weight': None,
					 'childWeightList': None,
					 'isClusterhead': None,
					 'state': "active",
					 'rackLocation': '2,4'},
				 '23': {'parentId': '22',
					 'childListId': ['38','37'],
					 'dist': None,
					 'clusterheadId': None,
					 'subtreeList': None,
					 'neighbourList': None,
					 'weight': None,
					 'childWeightList': None,
					 'isClusterhead': None,
					 'state': "active",
					 'rackLocation': '2,4'},
				 '24': {'parentId': '9',
					 'childListId': None,
					 'dist': None,
					 'clusterheadId': None,
					 'subtreeList': None,
					 'neighbourList': None,
					 'weight': None,
					 'childWeightList': None,
					 'isClusterhead': None,
					 'state': "active",
					 'rackLocation': '2,4'},
				 '25': {'parentId': '17',
					 'childListId': None,
					 'dist': None,
					 'clusterheadId': None,
					 'subtreeList': None,
					 'neighbourList': None,
					 'weight': None,
					 'childWeightList': None,
					 'isClusterhead': None,
					 'state': "active",
					 'rackLocation': '2,4'},
				 '26': {'parentId': '17',
					 'childListId': None,
					 'dist': None,
					 'clusterheadId': None,
					 'subtreeList': None,
					 'neighbourList': None,
					 'weight': None,
					 'childWeightList': None,
					 'isClusterhead': None,
					 'state': "active",
					 'rackLocation': '2,4'},
				 '27': {'parentId': '19',
					 'childListId': None,
					 'dist': None,
					 'clusterheadId': None,
					 'subtreeList': None,
					 'neighbourList': None,
					 'weight': None,
					 'childWeightList': None,
					 'isClusterhead': None,
					 'state': "active",
					 'rackLocation': '2,4'},
				 '28': {'parentId': '19',
					 'childListId': ['29'],
					 'dist': None,
					 'clusterheadId': None,
					 'subtreeList': None,
					 'neighbourList': None,
					 'weight': None,
					 'childWeightList': None,
					 'isClusterhead': None,
					 'state': "active",
					 'rackLocation': '2,4'},
				 '29': {'parentId': '28',
					 'childListId': None,
					 'dist': None,
					 'clusterheadId': None,
					 'subtreeList': None,
					 'neighbourList': None,
					 'weight': None,
					 'childWeightList': None,
					 'isClusterhead': None,
					 'state': "active",
					 'rackLocation': '2,4'},
				 '30': {'parentId': '20',
					 'childListId': None,
					 'dist': None,
					 'clusterheadId': None,
					 'subtreeList': None,
					 'neighbourList': None,
					 'weight': None,
					 'childWeightList': None,
					 'isClusterhead': None,
					 'state': "active",
					 'rackLocation': '2,4'},
				 '31': {'parentId': '7',
					 'childListId': ['32'],
					 'dist': None,
					 'clusterheadId': None,
					 'subtreeList': None,
					 'neighbourList': None,
					 'weight': None,
					 'childWeightList': None,
					 'isClusterhead': None,
					 'state': "active",
					 'rackLocation': '2,4'},
				 '32': {'parentId': '31',
					 'childListId': ['33'],
					 'dist': None,
					 'clusterheadId': None,
					 'subtreeList': None,
					 'neighbourList': None,
					 'weight': None,
					 'childWeightList': None,
					 'isClusterhead': None,
					 'state': "active",
					 'rackLocation': '2,4'},
				 '33': {'parentId': '32',
					 'childListId': None,
					 'dist': None,
					 'clusterheadId': None,
					 'subtreeList': None,
					 'neighbourList': None,
					 'weight': None,
					 'childWeightList': None,
					 'isClusterhead': None,
					 'state': "active",
					 'rackLocation': '2,4'},
				 '34': {'parentId': '21',
					 'childListId': ['35','36'],
					 'dist': None,
					 'clusterheadId': None,
					 'subtreeList': None,
					 'neighbourList': None,
					 'weight': None,
					 'childWeightList': None,
					 'isClusterhead': None,
					 'state': "active",
					 'rackLocation': '2,4'},
				 '35': {'parentId': '34',
					 'childListId': None,
					 'dist': None,
					 'clusterheadId': None,
					 'subtreeList': None,
					 'neighbourList': None,
					 'weight': None,
					 'childWeightList': None,
					 'isClusterhead': None,
					 'state': "active",
					 'rackLocation': '2,4'},
				 '36': {'parentId': '34',
					 'childListId': ['45'],
					 'dist': None,
					 'clusterheadId': None,
					 'subtreeList': None,
					 'neighbourList': None,
					 'weight': None,
					 'childWeightList': None,
					 'isClusterhead': None,
					 'state': "active",
					 'rackLocation': '2,4'},
				 '37': {'parentId': '23',
					 'childListId': ['43'],
					 'dist': None,
					 'clusterheadId': None,
					 'subtreeList': None,
					 'neighbourList': None,
					 'weight': None,
					 'childWeightList': None,
					 'isClusterhead': None,
					 'state': "active",
					 'rackLocation': '2,4'},
				 '38': {'parentId': '23',
					 'childListId': ['41','42'],
					 'dist': None,
					 'clusterheadId': None,
					 'subtreeList': None,
					 'neighbourList': None,
					 'weight': None,
					 'childWeightList': None,
					 'isClusterhead': None,
					 'state': "active",
					 'rackLocation': '2,4'},
				 '39': {'parentId': '13',
					 'childListId': ['50'],
					 'dist': None,
					 'clusterheadId': None,
					 'subtreeList': None,
					 'neighbourList': None,
					 'weight': None,
					 'childWeightList': None,
					 'isClusterhead': None,
					 'state': "active",
					 'rackLocation': '2,4'},
			     '40': {'parentId': '13',
					 'childListId': None,
					 'dist': None,
					 'clusterheadId': None,
					 'subtreeList': None,
					 'neighbourList': None,
					 'weight': None,
					 'childWeightList': None,
					 'isClusterhead': None,
					 'state': "active",
					 'rackLocation': '2,4'},
				 '41': {'parentId': '38',
					 'childListId': ['46'],
					 'dist': None,
					 'clusterheadId': None,
					 'subtreeList': None,
					 'neighbourList': None,
					 'weight': None,
					 'childWeightList': None,
					 'isClusterhead': None,
					 'state': "active",
					 'rackLocation': '2,4'},
				 '42': {'parentId': '38',
					 'childListId': ['47'],
					 'dist': None,
					 'clusterheadId': None,
					 'subtreeList': None,
					 'neighbourList': None,
					 'weight': None,
					 'childWeightList': None,
					 'isClusterhead': None,
					 'state': "active",
					 'rackLocation': '2,4'},
				 '43': {'parentId': '37',
					 'childListId': ['44'],
					 'dist': None,
					 'clusterheadId': None,
					 'subtreeList': None,
					 'neighbourList': None,
					 'weight': None,
					 'childWeightList': None,
					 'isClusterhead': None,
					 'state': "active",
					 'rackLocation': '2,4'},
				 '44': {'parentId': '43',
					 'childListId': None,
					 'dist': None,
					 'clusterheadId': None,
					 'subtreeList': None,
					 'neighbourList': None,
					 'weight': None,
					 'childWeightList': None,
					 'isClusterhead': None,
					 'state': "active",
					 'rackLocation': '2,4'},
				 '45': {'parentId': '36',
					 'childListId': None,
					 'dist': None,
					 'clusterheadId': None,
					 'subtreeList': None,
					 'neighbourList': None,
					 'weight': None,
					 'childWeightList': None,
					 'isClusterhead': None,
					 'state': "active",
					 'rackLocation': '2,4'},
				 '46': {'parentId': '41',
					 'childListId': None,
					 'dist': None,
					 'clusterheadId': None,
					 'subtreeList': None,
					 'neighbourList': None,
					 'weight': None,
					 'childWeightList': None,
					 'isClusterhead': None,
					 'state': "active",
					 'rackLocation': '2,4'},
				 '47': {'parentId': '42',
					 'childListId': ['48'],
					 'dist': None,
					 'clusterheadId': None,
					 'subtreeList': None,
					 'neighbourList': None,
					 'weight': None,
					 'childWeightList': None,
					 'isClusterhead': None,
					 'state': "active",
					 'rackLocation': '2,4'},
				 '48': {'parentId': '47',
					 'childListId': ['49'],
					 'dist': None,
					 'clusterheadId': None,
					 'subtreeList': None,
					 'neighbourList': None,
					 'weight': None,
					 'childWeightList': None,
					 'isClusterhead': None,
					 'state': "active",
					 'rackLocation': '2,4'},
				 '49': {'parentId': '48',
					 'childListId': None,
					 'dist': None,
					 'clusterheadId': None,
					 'subtreeList': None,
					 'neighbourList': None,
					 'weight': None,
					 'childWeightList': None,
					 'isClusterhead': None,
					 'state': "active",
					 'rackLocation': '2,4'},
				 '50': {'parentId': '39',
					 'childListId': None,
					 'dist': None,
					 'clusterheadId': None,
					 'subtreeList': None,
					 'neighbourList': None,
					 'weight': None,
					 'childWeightList': None,
					 'isClusterhead': None,
					 'state': "active",
					 'rackLocation': '2,4'}
				 }